dist: trusty
language: shell
branches:
  only:
  - main
  - /stablization-.*/
before_install:
- git clone https://$GIT_TOKEN@github.com/VipinPS/travis-scripts.git
- chmod +x travis-scripts/deploy.sh
- git fetch --all --tags
- export TAG=`git describe --tags --abbrev=0`
- export BRANCH="$TRAVIS_BRANCH"
deploy:
  skip_cleanup: true
  provider: script
  script: bash travis-scripts/deploy.sh 
  on:
    branch: 
    - main
    - /stablization-.*/
env:
  global:
  - TAG=`git describe --tags --abbrev=0`
  - BRANCH="$TRAVIS_BRANCH"
