dist: trusty
branches:
  only:
  - main
  - /stablization-.*/
before_install:
- git config core.sshCommand 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
- git clone git@github.ibm.com:Everest/travis-scripts.git
- chmod +x travis-scripts/deploy.sh
- git fetch --all --tags
- export TAG=`git describe --tags --abbrev=0`
- export BRANCH="$TRAVIS_BRANCH"
deploy:
  skip_cleanup: true
  provider: script
  script: bash travis-scripts/deploy.sh | tee travis-scripts/deploy.txt
  on:
    branch: 
    - master
    - /stablization-.*/
after_deploy: cat travis-scripts/deploy.txt
env:
  global:
  - TAG=`git describe --tags --abbrev=0`
  - BRANCH="$TRAVIS_BRANCH"
