dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - git fetch --all --tags
      - export TAG=`git describe --tags --abbrev=0`
      - export BRANCH="$TRAVIS_BRANCH"
      - export VERSION="${BRANCH}_${TAG}"
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t travis-ci-build-stages-demo .
      - docker images
      - docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/travis-ci-build-stages-demo:$VERSION
      - docker push $DOCKER_USERNAME/travis-ci-build-stages-demo:$VERSION
    - stage: test
      script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo:$VERSION cat hello.txt
    - script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo:$VERSION cat hello.txt
